language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
scala:
  - 2.10.3
jdk:
  - openjdk7
  - oraclejdk7
notifications:
  email:
    - heather.miller@epfl.ch
    - philipp.haller@typesafe.com
